[Bot]
server = ""
port = 0
nickname = ""
realname = ""
channel = ""
prefixes = []

[Modules]
enabled = []

[Modules.AutoURL]
ignore = ["youtube.com", "youtu.be"]

[Modules.Bofh]
excuse_path = "files/bofh_excuses.txt"

[Modules.Calc]

[Modules.Chuck]

[Modules.Example]

[Modules.Food]
api_key = ""

[Modules.Imdb]
api_key = ""

[Modules.Kanye]

[Modules.Youtube]
api_key = ""

[Modules.Zerox]
